### ISSUE TITLE
Associate cart more strongly with user 

### ISSUE THREAD

**Issue by tobinus** [tutturen/potato-store-front#36]
The problem is that is feels unintuitive that the cart follows you when you log out, and log in with another user. One solution is to clear the cart on logout, this is also the most realistic one. The second solution is to save the cart on the backend and associate it with the user, so you get it back when logging in.

**Comment by tutturen** [comment]
When implementing the Apollo architecture, I also added clearing the cart when you log out.

**Comment by tobinus** [comment]
Can confirm that this is fixed.
