### ISSUE TITLE
Indicate sales on cart page

### ISSUE THREAD

**Issue by tobinus** [tutturen/potato-store-front#37]
Like #33, but for the cart page.

**Comment by tobinus** [comment]
This was fixed for percentage sales in 0b4f5e9a3

**Comment by tutturen** [comment]
As we just indicate "price without sale" and price with "all sales", I think this is fixed for both percentage sales and package deals now.

**Comment by tobinus** [comment]
The total with and without sales seems correct.

There are two things I'd like to take a look at:
1. Per-item percentage sales shows how much was cut, not the actual price
2. No indication is made for package deals per item

I'd like to take a look at those two.

**Comment by tobinus** [comment]
Okay, we need to merge in tutturen/potato-store#66 to fix the per-item percentage calculation being wrong.
