### ISSUE TITLE
Let the customer pick quantities of items to buy

### ISSUE THREAD

**Issue by tobinus** [tutturen/potato-store-front#55]
Currently, we let the customer buy multiple products. It would be nice if the customer could easily pick the quantity of an item.

- [ ] Let the customer pick quantity before or as a part of adding the product to the cart.
- [x] Let the customer change the quantity when displaying the cart
- [x] Adapt to the required changes in the GraphQL API (potato-store-front)

**Comment by tutturen** [comment]
What about not letting the customer pick quantity when adding products, but just in the cart?
That is how i.e. `komplett.no` does it.

**Comment by tobinus** [comment]
That's alright. I first thought the assignment description implied that we needed to implement that, but I think we can satisfy the requirement "As a user, I want to be able to be able to choose the quantity I want of some item" without that.

**Comment by tobinus** [comment]
Fixed in #58
